name: Issue closer.

on:
  issues:
    types: opened

jobs:
  comment:
    runs-on: ubuntu-slim
    steps:
      - name: Process an issue.
        uses: desktop-app/action_issue_closer@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
